// wasm/examples/vue/MoleculePanel.vue
<script setup>
import { onBeforeUnmount, onMounted, ref, watch } from "vue";
import init, { Molecule } from "@cosmol-studio/cosmolkit";

const props = defineProps({ smiles: { type: String, default: "CCO" } });
const molecule = ref(null);
const error = ref("");
let ready = false;

function update() {
  if (!ready) return;
  try {
    const next = Molecule.fromSmiles(props.smiles);
    molecule.value?.free();
    molecule.value = next;
    error.value = "";
  } catch (value) {
    error.value = String(value);
  }
}

onMounted(async () => {
  try {
    await init();
    ready = true;
    update();
  } catch (value) {
    error.value = String(value);
  }
});

watch(() => props.smiles, update);
onBeforeUnmount(() => molecule.value?.free());
</script>

<template>
  <pre v-if="error">{{ error }}</pre>
  <output v-else-if="molecule">{{ molecule.toSmiles() }}</output>
  <p v-else>Loading COSMolKit...</p>
</template>

// wasm/examples/react/MoleculePanel.jsx
import { useEffect, useState } from "react";
import init, { Molecule } from "@cosmol-studio/cosmolkit";

export function MoleculePanel({ smiles = "CCO" }) {
  const [ready, setReady] = useState(false);
  const [molecule, setMolecule] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    let active = true;
    init()
      .then(() => active && setReady(true))
      .catch((value) => active && setError(String(value)));
    return () => {
      active = false;
    };
  }, []);

  useEffect(() => {
    if (!ready) return undefined;
    try {
      const next = Molecule.fromSmiles(smiles);
      setMolecule(next);
      setError("");
    } catch (value) {
      setError(String(value));
    }
    return undefined;
  }, [ready, smiles]);

  useEffect(() => () => molecule?.free(), [molecule]);

  if (error) return <pre>{error}</pre>;
  if (!molecule) return <p>Loading COSMolKit...</p>;
  return <output>{molecule.toSmiles()} ({molecule.numAtoms()} atoms)</output>;
}
